services:
  db:
    image: imresamu/postgis:15-3.4
    container_name: farmland_postgis
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: farmland_db
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d farmland_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgis_data:
